// Serves a WebP with a JPG fallback. `src` is the original JPG path
// (e.g. "/harvard-team.jpg"); the .webp sibling is generated by
// scripts/convert-images.mjs. The <img> keeps the styling class, and the
// global `picture { display: contents }` rule keeps layout identical to a
// bare <img>.
export default function Picture({ src, alt, className, loading = 'lazy', decoding = 'async', fetchPriority, ...rest }) {
  const webp = src.replace(/\.jpe?g$/i, '.webp')
  return (
    <picture>
      <source srcSet={webp} type="image/webp" />
      <img
        src={src}
        alt={alt}
        className={className}
        loading={loading}
        decoding={decoding}
        fetchpriority={fetchPriority}
        {...rest}
      />
    </picture>
  )
}
