import manifest from '../image-manifest.json'

// Serves a WebP with a JPG fallback. `src` is the original JPG path
// (e.g. "/harvard-team.jpg"); the .webp sibling and its narrower variants are
// generated by scripts/convert-images.mjs. The <img> keeps the styling class,
// and the global `picture { display: contents }` rule keeps layout identical
// to a bare <img>.
//
// The widths come from src/image-manifest.json rather than being assumed, so
// the srcset can never point at a variant that was not generated — photos
// smaller than a given width are skipped by the script instead of upscaled.
//
// `sizes` is not optional in practice: with w-descriptors a missing sizes
// means 100vw, and the browser would pick the largest file for an image
// displayed at 289px. Every call site passes its real layout width.
export default function Picture({
  src,
  alt,
  className,
  sizes = '100vw',
  loading = 'lazy',
  decoding = 'async',
  fetchPriority,
  ...rest
}) {
  const webp = src.replace(/\.jpe?g$/i, '.webp')
  const info = manifest[src]
  const srcSet = info
    ? [
        ...info.widths.map(w => `${webp.replace(/\.webp$/, `-${w}.webp`)} ${w}w`),
        `${webp} ${info.full}w`,
      ].join(', ')
    : webp

  return (
    <picture>
      <source type="image/webp" srcSet={srcSet} sizes={info ? sizes : undefined} />
      <img
        src={src}
        alt={alt}
        className={className}
        loading={loading}
        decoding={decoding}
        fetchpriority={fetchPriority}
        {...rest}
      />
    </picture>
  )
}
