export const NAV_LINKS = ['About', 'Experience', 'Journey', 'Projects', 'Highlights', 'Globe', 'Research', 'Skills', 'Leadership', 'Contact']
export const RECRUITER_NAV = ['About', 'Experience', 'Projects', 'Research', 'Skills', 'Contact']

export const EXPERIENCE = [
  {
    title: 'Program Manager & Scrum Master',
    company: 'MSIG USA',
    monogram: 'MSIG',
    brandColor: '#c8161d',
    logo: null,
    type: 'Co-op',
    location: 'Warren, NJ',
    period: 'Jan 2026 – Present',
    description: 'Serving as the operational and delivery anchor for the Data & AI team — spanning agile delivery, PI planning, hiring operations, ADO governance, and executive reporting across Claims Data, Re-insurance and Finance Data, and Strategic Projects.',
    bullets: [
      'Facilitating daily standups for Claims Data, Fabric, and Data Operations teams; managing Azure DevOps boards, resolving access issues, and aligning sprint work items with PI planning inputs across multiple concurrent workstreams',
      'Co-authored Q2 2026 PI Planning Kick-off deck and led dependency coordination across Claims, Actuarial, Finance, and Data Platforms; translated capacity planning inputs into ADO-ready line items',
      'Developed the PCT/Prosci Change Triangle Assessment Framework — a 29-deliverable, 16-condition project health methodology presented to VP/Director leadership as a proposed organizational standard',
      'Co-authoring EDM Monthly Status Tracking decks for leadership covering onboarding throughput, interview pipeline, risks, and mitigations; acting as trusted operational anchor for delivery directors and data leads',
      'Supporting Microsoft Fabric tenant-to-tenant migration across database tables and delivering Fabric enablement training for 20 actuarial participants on F64 capacity',
    ],
    tags: ['Microsoft Fabric', 'Azure DevOps', 'Scrum / Agile', 'PI Planning', 'Change Management', 'Hiring Operations', 'Executive Reporting', 'Prosci'],
    current: true,
  },
  {
    title: 'Co-Founder & Chief Product Officer',
    company: 'Cratel',
    monogram: 'CR',
    brandColor: '#8b83e4',
    logo: null,
    type: 'Startup',
    location: 'Bengaluru, India',
    period: 'Jun 2023 – Apr 2024',
    description: 'Co-founded a B2C e-commerce startup streamlining supply chains by connecting producers directly to consumers.',
    bullets: [
      'Designed platform that reduced consumer costs by 40% through direct producer-consumer connections',
      'Implemented process optimizations cutting operational costs by 25%',
      'Developed data-driven should-cost models for IoT hardware procurement',
      'Established supplier selection frameworks and quality control procedures',
    ],
    tags: ['Product Strategy', 'Supply Chain', 'Should-Cost Modeling', 'Team Leadership'],
    current: false,
  },
  {
    title: 'Program Manager',
    company: 'Office of Dean of Student Affairs, PES University',
    monogram: 'PES',
    brandColor: '#005baa',
    logo: null,
    type: null,
    location: 'Bengaluru, India',
    period: 'Jun 2023 – Jan 2024',
    description: 'Operational lead for the Dean\'s office, overseeing a broad portfolio of student programs and organizations.',
    bullets: [
      'Directed 1,000+ student volunteers and organized university-wide events for audiences up to 10,000',
      'Managed $350,000+ in annual funding across 50+ student organizations',
      'Designed automated event approval system reducing administrative turnaround time by 60%',
    ],
    tags: ['Event Management', 'Budget Oversight', 'Stakeholder Management', 'SOPs'],
    current: false,
  },
]

export const PROJECTS = [
  {
    id: 'spidey',
    featured: true,
    title: '"Spidey Sense"',
    subtitle: 'Haptic VR Accessibility Device',
    context: 'MIT Reality Hack 2025 · Project Manager · Team of 5 · 48-Hour Hackathon',
    description: 'Led a multidisciplinary team to develop a wearable haptic navigation device making VR accessible to visually impaired users. Meta Quest 3 cameras map surroundings and translate obstacles into real-time vibration patterns.',
    bullets: [
      'Built around ESP32 microcontroller with custom pancake vibration motors via DRV8833 drivers',
      'Bluetooth Low Energy integration with Meta Quest 3 — feedback latency under 50ms',
      '95% improvement in navigation confidence among visually impaired test users',
      'Patent application initiated for haptic feedback algorithm',
      'Won "Jaw-Dropping Award" in Hardware Track from 100+ international teams',
    ],
    tags: ['ESP32', 'C++', 'VR Development', 'Bluetooth LE', 'Meta Quest 3', 'Hardware Design'],
    award: 'Jaw-Dropping Award · MIT Reality Hack 2025',
    caseStudy: {
      tldr: 'A wrist-worn haptic device that lets visually impaired users feel a virtual environment in real time.',
      role: 'Project Manager',
      duration: '48 hours',
      team: 'Team of 5 · multidisciplinary',
      problem: 'VR has become rich and immersive, but it remains inaccessible to the visually impaired — virtual obstacles can\'t be seen and there is no equivalent of a white cane inside VR. We set out to build a wearable that translates spatial information into touch, in under 48 hours, using only off-the-shelf hardware.',
      approach: [
        'Wired an ESP32 microcontroller to a custom array of pancake vibration motors driven by DRV8833 motor drivers — chosen for compactness and sub-50ms response.',
        'Streamed depth data from Meta Quest 3 cameras over Bluetooth Low Energy to the wristband, encoding obstacle direction and proximity as distinct vibration patterns.',
        'Tuned the haptic vocabulary with visually impaired test users on-site at MIT, iterating on intensity, motor placement, and pattern grammar.',
      ],
      metrics: [
        { value: '<50ms', label: 'Feedback latency' },
        { value: '95%', label: 'Confidence gain' },
        { value: '100+', label: 'Teams beaten' },
        { value: 'Patent', label: 'Filed' },
      ],
      learnings: 'Hardware hackathons live and die by scope discipline. We cut three "nice-to-haves" by hour 18 and shipped a working demo to judges with battery to spare — that focus was what won the room.',
    },
  },
  {
    id: 'warehouse',
    featured: false,
    title: 'Warehouse Automation Optimization',
    subtitle: null,
    context: 'Northeastern University · Supply Chain Engineering',
    description: 'Redesign of a mid-sized e-commerce warehouse handling 50,000+ monthly orders, exploring automation while preserving human-machine collaboration.',
    bullets: [
      '25% increase in operational efficiency with 18-month ROI payback period',
      '$280K annual savings through labor optimization and error reduction',
      '40% reduction in average pick-walk distance',
    ],
    tags: ['Operations Research', 'AGV Systems', 'WMS', 'ROI Analysis'],
    award: null,
    caseStudy: {
      tldr: 'Operations-research redesign of a 50K-order/month warehouse balancing AGV automation with skilled human picking.',
      role: 'Lead Analyst',
      duration: 'Semester project',
      team: 'Northeastern Supply Chain Engineering',
      problem: 'A mid-sized e-commerce warehouse was hitting throughput ceilings on every peak season. Labor-only and automation-only approaches both fell apart on the numbers — labor didn\'t scale, automation didn\'t pencil out. The brief was to find a hybrid layout that paid back in under two years.',
      approach: [
        'Modeled current pick paths, labor utilization, and error rates against three layout variants (zone, batch, hybrid AGV).',
        'Quantified the cost-of-error and shrink curves to expose the breakpoint where AGVs justified themselves.',
        'Built an ROI model with three demand scenarios so the recommendation survived contact with peak-season uncertainty.',
      ],
      metrics: [
        { value: '25%', label: 'Throughput lift' },
        { value: '$280K', label: 'Annual savings' },
        { value: '40%', label: 'Walk distance cut' },
        { value: '18mo', label: 'ROI payback' },
      ],
      learnings: 'The cleanest ROI story came from removing pick-walk distance, not buying robots — operations research wins are usually about geometry before they\'re about technology.',
    },
  },
  {
    id: 'uav',
    featured: false,
    title: 'Digital Twin of UAVs',
    subtitle: null,
    context: 'PES University · Research Project',
    description: 'Comprehensive digital twin framework for UAVs — a real-time virtual replica fed by live sensor data to predict behavior and failures without risking hardware.',
    bullets: [
      '95% accuracy in flight parameter prediction, 88% in failure prediction',
      'Sub-100ms latency Unity physics environment with ROS sensor fusion',
      'Submitted to IEEE Transactions on Aerospace and Electronic Systems',
    ],
    tags: ['ROS', 'Unity 3D', 'Machine Learning', 'LiDAR', 'Kafka'],
    award: null,
    caseStudy: {
      tldr: 'A live virtual replica of a UAV that predicts flight parameters and failures from streaming sensor data.',
      role: 'Research Lead',
      duration: 'Multi-semester research project',
      team: 'PES University · Aerospace + ML',
      problem: 'Testing UAV failure modes on real hardware is slow, expensive, and risky. Existing simulators don\'t reflect the real airframe\'s wear or sensor noise — so failure predictions don\'t transfer. We wanted a digital twin that learned from the actual aircraft\'s telemetry.',
      approach: [
        'Streamed ROS sensor data (IMU, GPS, LiDAR) into a Unity physics environment under 100ms.',
        'Fused real and simulated state through Kafka to train ML models on aligned data.',
        'Trained a flight-parameter predictor and a failure-mode classifier; validated both against held-out flight logs.',
      ],
      metrics: [
        { value: '95%', label: 'Param prediction' },
        { value: '88%', label: 'Failure prediction' },
        { value: '<100ms', label: 'Sim latency' },
        { value: 'IEEE', label: 'Submitted' },
      ],
      learnings: 'Closing the sim-to-real gap was less about better physics and more about better data plumbing — alignment between real and simulated state mattered more than fidelity of either side.',
    },
  },
  {
    id: 'pct',
    featured: false,
    title: 'PCT Assessment Framework',
    subtitle: 'Organizational Change Methodology',
    context: 'MSIG USA · Data & AI Team · 2025',
    description: 'Designed a project health assessment framework based on the Prosci Change Triangle — combining 29 deliverables and 16 conditions to evaluate organizational readiness and change adoption for enterprise data initiatives.',
    bullets: [
      '29-deliverable assessment covering leadership, project management, and change management dimensions',
      '16-condition health scoring model for real-time project risk visibility',
      'Built on Prosci ADKAR methodology with custom adaptations for data platform delivery',
    ],
    tags: ['Prosci', 'Change Management', 'ADKAR', 'Organizational Design', 'Risk Assessment'],
    award: null,
    caseStudy: {
      tldr: 'A 29-deliverable, 16-condition project health framework presented to VP/Director leadership as a candidate organizational standard.',
      role: 'Program Manager',
      duration: 'Q1–Q2 2026',
      team: 'MSIG USA Data & AI',
      problem: 'Enterprise data initiatives at MSIG were measured by delivery velocity but not by organizational readiness — projects shipped on time and still failed adoption. Leadership needed a single, repeatable assessment that surfaced change-risk early, not at go-live.',
      approach: [
        'Mapped the Prosci Change Triangle to MSIG\'s actual data delivery workflow, identifying the gaps a standard ADKAR assessment didn\'t cover.',
        'Codified 29 concrete deliverables (artifacts, decisions, sign-offs) and 16 health conditions (leadership engagement, sponsor coverage, stakeholder alignment, etc.).',
        'Pitched the framework to VP/Director leadership as a proposed standard for all enterprise data initiatives.',
      ],
      metrics: [
        { value: '29', label: 'Deliverables' },
        { value: '16', label: 'Health conditions' },
        { value: 'VP', label: 'Audience' },
        { value: 'Q2 2026', label: 'Presented' },
      ],
      learnings: 'Change frameworks fail when they live in slide decks. The version that survived was the one I shrank into a one-pager with a scoring rubric a delivery lead could complete in an hour.',
    },
  },
]

// `shape` drives the frame aspect-ratio in a masonry layout so each photo
// keeps its native orientation instead of being cropped into one box.
// portrait = 4:5, landscape = 4:3, wide = 16:9.
export const HIGHLIGHTS = [
  {
    img: '/msig-ceo-award.jpg',
    title: 'MSIG USA CEO Award — "You Make a Difference"',
    sub: 'Tech & Operations · Data & AI Team · 2026',
    badge: 'Award',
    shape: 'portrait',
    feature: true,
  },
  {
    img: '/mit-rh-mentor.jpg',
    title: 'With the best mentor at MIT Reality Hack',
    sub: 'A 48-hour build, made possible by the people in the room',
    badge: null,
    shape: 'landscape',
  },
  {
    img: '/mit-scm-session.jpg',
    title: 'MIT Supply Chain Sessions',
    sub: 'Northeastern × MIT speaker series',
    badge: null,
    shape: 'portrait',
  },
  {
    img: '/harvard-team.jpg',
    title: 'Harvard Asian Business Conference',
    sub: 'Cambridge, MA · 2025',
    badge: null,
    shape: 'landscape',
  },
  {
    img: '/mit-souvenir.jpg',
    title: 'MIT lecture · Prof. Miguel Rodriguez García',
    sub: 'Team souvenir for solving the day\'s problem',
    badge: null,
    shape: 'portrait',
  },
  {
    img: '/mit-rh-team.jpg',
    title: 'MIT Reality Hack 2025',
    sub: 'Hardware Track winner · Team behind "Spidey Sense"',
    badge: 'Award',
    shape: 'wide',
  },
]

export const RESEARCH = {
  papers: [
    {
      title: 'Bridging the Accuracy-Explainability Gap: A Hybrid ARIMA-LLM Architecture for Demand Forecasting',
      authors: 'Yashaswi Alur Prasannakumar, Dr. Nada R. Sanders',
      venue: 'Under Review · Targeting INFORMS & POMS',
      status: 'under-review',
      description: 'A novel hybrid forecasting architecture integrating ARIMA\'s statistical rigor with LLM explainability — addressing the critical gap in enterprise supply chain tools where black-box predictions impede trust and adoption. Achieved statistical equivalence to pure ARIMA (40.61% vs. 38.44% MAPE, p=0.0524) while adding natural language explanations. Particularly strong on high-volatility items: +13.18 pp improvement over baseline.',
      highlights: [
        'LangGraph orchestration framework with Human-in-the-Loop escalation achieving 100% routing accuracy',
        'Chess-engine-inspired forecast confidence visualizer for practitioner transparency',
        'Between-subjects user study validating explainability impact on decision quality',
      ],
      tags: ['ARIMA', 'LLM', 'LangGraph', 'Supply Chain Forecasting', 'Time Series', 'Python', 'HITL'],
    },
    {
      title: 'Multi-Dimensional Trust Calibration for Human-in-the-Loop AI Decision Systems: Evidence from Supply Chain Planning',
      authors: 'Yashaswi Alur Prasannakumar, Dr. Nada R. Sanders',
      venue: 'Under Review · Targeting INFORMS & POMS',
      status: 'under-review',
      description: 'Investigates how trust in AI-assisted decision systems can be systematically calibrated across multiple dimensions in supply chain planning contexts. Examines the interplay between model transparency, human oversight, and decision quality in high-stakes operational settings.',
      highlights: [],
      tags: ['Human-in-the-Loop', 'AI Trust', 'Decision Systems', 'Supply Chain', 'Behavioral Research'],
    },
    {
      title: 'Deep Learning-Based Blockage Prediction for IRS-Aided V2X Networks',
      authors: 'Yashaswi Alur Prasannakumar et al.',
      venue: 'Published · WiSPNET 2024',
      status: 'published',
      description: 'Implemented and compared CNN, GRU, and LSTM models for predicting mm-Wave link blockages in vehicular networks using the ViWi dataset. Demonstrated how Intelligent Reflecting Surfaces improve prediction accuracy and SNR.',
      highlights: [],
      tags: ['CNN', 'GRU', 'LSTM', 'mm-Wave', 'V2X', 'IRS'],
    },
    {
      title: 'IRS-Assisted mm-Wave Blockage Prediction in Vehicular Environments',
      authors: 'Yashaswi Alur Prasannakumar et al.',
      venue: 'Published · PES University Research · 2024',
      status: 'published',
      description: 'ML-based obstacle prediction in high-mobility V2X environments, focusing on NLOS communication reliability and model generalization across urban mobility scenarios via intelligent reflecting surfaces.',
      highlights: [],
      tags: ['Machine Learning', 'V2X', 'NLOS', 'IRS', 'Vehicular Networks'],
    },
  ],
}

export const SKILLS = {
  'Program & Project Management': ['Scrum / Agile', 'Azure DevOps', 'Sprint Planning', 'Change Management', 'Stakeholder Communication', 'Risk Management', 'Roadmapping', 'Prosci / ADKAR'],
  'Data & Analytics': ['Microsoft Fabric', 'Power BI', 'Python (Pandas, NumPy, sklearn)', 'SQL', 'Machine Learning', 'LLMs & LangGraph', 'Time Series Analysis', 'Data Pipelines & ETL'],
  'Supply Chain & Operations': ['Strategic Sourcing', 'Should-Cost Modeling', 'Vendor Evaluation', 'Process Optimization', 'Demand Forecasting', 'ERP Systems', 'ROI Analysis', 'Quality Control'],
  'Engineering & Technical': ['MATLAB', 'ROS', 'Unity 3D', 'Google Cloud / Vertex AI', 'Microsoft Azure', 'C++', 'REST APIs', 'Apache Airflow'],
}

export const LEADERSHIP = [
  {
    role: 'Head of Hardware Sponsorship',
    org: 'MIT Reality Hack 2027',
    period: 'Active',
    current: true,
    description: 'Leading hardware sponsorship operations for one of the world\'s premier XR hackathons at MIT, coordinating with industry partners to source and deliver hardware for participants.',
  },
  {
    role: 'Senator',
    org: 'Graduate Student Government, Northeastern University',
    period: '2025 – 2026',
    current: false,
    description: 'Represented graduate student interests at Northeastern University, participating in institutional policy discussions and funding decisions.',
  },
  {
    role: 'Community Chair & Executive Committee Member',
    org: 'Intercollegiate XR (ICXR)',
    period: 'Mar 2025 – Mar 2026',
    current: false,
    description: 'Led the world\'s premier collegiate XR community — organizing multi-campus hackathons, managing industry partnerships, and coordinating VR equipment sharing across universities. Resigned March 2026.',
  },
  {
    role: 'Founder & Club Head',
    org: 'Shunya: The Math Club, PES University',
    period: 'Nov 2021 – May 2024',
    current: false,
    description: '200+ active contributors across campuses, ₹20L prize Arithemania 2.0 hackathon, sponsorships from MathWorks and Wolfram, and community math outreach in government schools.',
  },
  {
    role: 'Founder & Advisor',
    org: 'IRA PESU — Socio-Cultural Club, PES University',
    period: '2022 – 2024',
    current: false,
    description: 'Established IRA PESU to celebrate national and cultural festivals across the university campus, building a community-driven platform for cultural events and student engagement.',
  },
  {
    role: 'Founding Member & Advisor',
    org: 'HoPES — Official Media Club, PES University',
    period: '2022 – 2024',
    current: false,
    description: 'One of the founding members of PES University\'s official media club — contributed to major institutional decisions, content strategy, and organizational direction as an advisor.',
  },
  {
    role: 'Student Head',
    org: 'Bharat Unleashed — Golden Jubilee Celebrations, PES University',
    period: 'Jan 2024',
    current: false,
    description: 'Student lead for PES University\'s 50th anniversary celebrations — a 4-day flagship event featuring distinguished speakers, cultural performances by Shankar Mahadevan, and a conclave attended by Smt. Sudha Murthy and other luminaries.',
  },
  {
    role: 'Head of Logistics',
    org: 'Aikya — Social Service Club, PES University',
    period: '2022 – 2024',
    current: false,
    description: 'Managed logistics for social service drives, school outreach programs teaching underprivileged children, hackathons, and donation drives at this Akshaya Patra-inspired community initiative.',
  },
  {
    role: 'Founding Member & Head of Operations',
    org: 'Apple Developers Group, PES University',
    period: '2022 – 2024',
    current: false,
    description: 'Looked after operations and logistics for workshops, technical talks, and engineering events organized by the Apple Developers Group on campus.',
  },
  {
    role: 'Founding Member & Executive Committee',
    org: 'IEEE Signal Processing & Communication Society, PES University',
    period: 'Apr 2022 – Jun 2024',
    current: false,
    description: 'Organized national-level workshops, signal processing bootcamps, and IEEE-sponsored hackathons connecting students with 5G and AI-driven communications industry professionals.',
  },
  {
    role: 'Event Head & Advisor',
    org: 'Samarpana — Annual Armed Forces Tribute, PES University',
    period: 'Jun 2022 – Dec 2023',
    current: false,
    description: 'Led 1,000+ volunteers for a 4-day national event honoring the Indian Armed Forces, featuring Padma Shri A.S. Kiran Kumar as Chief Guest and talks by Kargil War veterans. 10,000+ attendees. Continued as Advisor in 2023.',
  },
  {
    role: 'Co-Founder',
    org: 'Cratel — B2C E-Commerce Startup',
    period: 'Jun 2023 – Apr 2024',
    current: false,
    description: 'Co-founded and led product strategy for a B2C supply chain startup, reducing consumer costs by 40% through direct producer-consumer connections.',
  },
]
